apiVersion: v1
kind: Service
metadata:
  name: yuvaraj-portfolio-service
spec:
  type: NodePort
  selector:
    app: yuvaraj-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080